import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as echarts from 'echarts/core';
import {LineChart,BarChart} from 'echarts/charts';
import {GridComponent,TooltipComponent,LegendComponent,AriaComponent} from 'echarts/components';
import {SVGRenderer} from 'echarts/renderers';
import D from '../data/dashboard.json';
import './style.css';
echarts.use([LineChart,BarChart,GridComponent,TooltipComponent,LegendComponent,AriaComponent,SVGRenderer]);
const K=D.kpi, teal='#087E8B',blue='#315EE8',gray='#607486',amber='#98621D';
const num=(n,d=0)=>new Intl.NumberFormat('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}).format(n);
const pct=(n,d=2)=>num(n*100,d)+'%';
const issueNames={'Delivery waiting / non-receipt':'等待／尚未收到','Incomplete order / missing units':'少件／部分收到','Product condition / mismatch':'商品状态／不符（宽类别）','Mixed resolution / service':'混合解决／服务','Generic / Unclear':'泛化／不明确','Mixed / rating-text mismatch':'混合／评分文本不一致','Positive delivery mentions':'正向交付表达','Positive generic mentions':'泛化好评','Positive product / overall mentions':'正向商品／整体体验'};
const factorNames={unique_customers:'用户规模',purchase_frequency:'购买频次',aov:'AOV'};
const titles=['平台经营总览','商家增长','客户价值','履约与体验','AI Voice of Customer'];
const routes=['overview','seller','customer','fulfillment','ai-voc'];
const subtitles=['增长、商家与客户体验，放在同一经营视野中','从线索转化到成熟 Seller 表现，保持覆盖范围透明','复购观察、成熟窗口与客户结构，避免过度细分','区分评价时点，再解释履约与评分的关联','语义发现 → 经营验证 · Exploratory AI'];
function Chart({id,labels,series,kind='bar',horizontal=false,percent=false,max,height=230,decimals=1,legend=false}){
 const ref=useRef();const unit=percent?'%':'';
 useEffect(()=>{
  if(!labels.length)return;
  const c=echarts.init(ref.current,null,{renderer:'svg'});
  const valueAxis={type:'value',min:series.some(s=>s.values.some(v=>v<0))?null:0,max:max??null,axisLabel:{color:gray,fontSize:10,formatter:v=>num(v,max&&max<=4?1:0)+unit},splitLine:{lineStyle:{color:'#E5EBF0'}}};
  const catAxis={type:'category',data:labels,axisTick:{show:false},axisLine:{show:false},axisLabel:{color:gray,fontSize:11,interval:kind==='line'?(i=>labels.length<7||i%6===0||i===labels.length-1):0,showMinLabel:true,showMaxLabel:true,hideOverlap:true}};
  c.setOption({animation:false,aria:{enabled:true},color:[teal,blue,gray,amber],grid:{left:horizontal?12:8,right:28,top:legend?36:18,bottom:12,containLabel:true},legend:{show:legend,top:0,textStyle:{color:gray,fontSize:11}},tooltip:{trigger:'axis',confine:true,backgroundColor:'#fff',borderColor:'#D7E1E7',textStyle:{color:'#172B3B',fontSize:12},formatter:params=>{const p=Array.isArray(params)?params:[params];return p[0].axisValueLabel+'<br/>'+p.map(t=>t.marker+t.seriesName+': '+num(t.value,decimals)+unit).join('<br/>');}},xAxis:horizontal?valueAxis:catAxis,yAxis:horizontal?{...catAxis,inverse:true}:valueAxis,series:series.map(s=>({name:s.name,type:kind,data:s.pointColors?s.values.map((v,i)=>({value:v,itemStyle:{color:s.pointColors[i]}})):s.values,itemStyle:{color:s.color},lineStyle:{width:3,type:s.dashed?'dashed':'solid'},symbol:'circle',symbolSize:5,showSymbol:kind!=='line',barMaxWidth:16,label:{show:horizontal,position:'right',fontSize:11,color:gray,formatter:v=>num(v.value,decimals)+unit},emphasis:{focus:'series'}}))});
  const resize=new ResizeObserver(()=>c.resize());resize.observe(ref.current);return()=>{resize.disconnect();c.dispose();};
 },[id,labels.join('|'),JSON.stringify(series),kind,horizontal,percent,max,height,legend]);
 if(!labels.length)return <div className="no-data" role="status">No data for selected filters<br/><span>当前筛选无数据，请调整条件或重置。</span></div>;
 return <><div ref={ref} id={id} className="chart" style={{height}} role="img" aria-label={labels.map((l,i)=>l+': '+series.map(s=>s.name+' '+num(s.values[i],decimals)+unit).join('，')).join('；')} data-labels={labels.join('|')} data-series={JSON.stringify(series.map(s=>s.values))}/><details className="data-table"><summary>查看图表数据</summary><table><thead><tr><th>项目</th>{series.map(s=><th key={s.name}>{s.name}{unit}</th>)}</tr></thead><tbody>{labels.map((l,i)=><tr key={l}><td>{l}</td>{series.map(s=><td key={s.name}>{num(s.values[i],decimals)}</td>)}</tr>)}</tbody></table></details></>;
}
function Card({title,sub,children,actions,className=''}){return <section className={'card '+className}><div className="card-head"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{actions&&<div className="actions">{actions}</div>}</div>{children}</section>;}
function Kpis({items}){return <div className="kpi-row" style={{'--count':items.length}}>{items.map(([label,value,note])=><div className="kpi" key={label}><i/><div className="kpi-label">{label}</div><strong title={note}>{value}</strong><p>{note}</p></div>)}</div>;}
function Select({label,value,onChange,options}){return <label className="filter">{label}<select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>;}
function Hero(){return <div className="hero">{D.hero.map((r,i)=><div className="hero-row" key={r.label}><div><span>{r.label.replace("签收后正文", "签收后作答正文")}</span><strong className={i===0?'warning':''}>{pct(r.rate)}</strong></div><div className="track"><div style={{width:(r.rate/.6*100)+'%',background:i===0?amber:teal}}/></div><small>迟到 {num(r.num)} / 有效正文 {num(r.den)}</small></div>)}<p className="caption">共同刻度 0–60% · 签收后按 review_answer_timestamp 判定。评价时点实质改变解释，非干预前后改善。</p></div>;}
function Office(){return <><Chart id="office-structure" horizontal percent max={30} decimals={1} height={179} legend labels={D.office.map(r=>issueNames[r.issue])} series={[{name:'Office Furniture',color:blue,values:D.office.map(r=>r.rate*100)},{name:'核心主问题基线',color:gray,values:D.office.map(r=>r.baseline*100)}]}/><p className="caption">主问题正文内结构：办公家具 n={num(D.office[0].den)}；基线 n={num(D.office[0].baselineDen)}。Diagnostic Signal，非全平台投诉概率。</p></>;}
function Overview(){
 const [metric,setMetric]=useState('gmv');
 return <><Kpis items={[["GMV · BRL",num(K.gmv/1e6,2)+'M','精确 '+num(K.gmv,2)+' BRL · 商品金额'],['已签收订单',num(K.orders),'2017-01 至 2018-07'],['July GMV YoY','+'+pct(K.julyYoY),'2018-07 对比 2017-07'],['迟到率',pct(K.late),num(K.lateN)+' / '+num(K.lateDen)+' 有效日期订单'],['观测复购率',pct(K.repeat),num(K.repeatCount)+' / '+num(K.customers)+' 购买用户']]}/>
 <div className="focus-banner"><b>经营关注</b><span>增长分解以用户规模为主</span><span>观测复购 {pct(K.repeat)}</span><span>评价时点改变 AI VOC 解读</span></div>
 <div className="overview-top"><Card title="平台月度趋势" sub="购买月 · 核心已签收订单；图内切换不改变全期 KPI" actions={<Select label="趋势指标" value={metric} onChange={setMetric} options={[["gmv","GMV · 百万 BRL"],["orders","已签收订单"]]}/> }><Chart id="monthly-trend" kind="line" labels={D.monthly.map(r=>r.month)} series={[{name:metric==='gmv'?'GMV（百万BRL）':'订单',values:D.monthly.map(r=>metric==='gmv'?r.gmv/1e6:r.orders)}]} max={metric==='gmv'?1.2:undefined} decimals={metric==='gmv'?3:0} height={240}/></Card>
 <Card title="July YoY 增长分解" sub="对 GMV 增量的贡献份额，合计 100%"><Chart id="growth-decomposition" horizontal percent max={100} decimals={2} labels={D.decomposition.map(r=>factorNames[r.factor])} series={[{name:'数学贡献份额',values:D.decomposition.map(r=>r.share*100)}]} height={225}/><p className="caption">Mathematical contribution, not causal attribution.<br/>用户规模、频次与 AOV 的数学分解，不是因果贡献。</p></Card></div>
 <div className="overview-bottom"><Card title="评价时点改变解读" sub="等待／未收到主题 · 核心正文迟到率"><Hero/></Card><Card title="客户回访观察" sub="不同分母，不能视为同一个转化漏斗"><Chart id="return-signals" horizontal percent max={4} decimals={2} height={220} labels={['观测复购','共同成熟 90D','90D · ≥24h敏感性']} series={[{name:'比例',color:blue,values:[K.repeat*100,K.rep90*100,K.rep24*100]}]}/><p className="caption">约 {pct(K.oneTime,0)} 用户仅一单；成熟窗口指标见客户价值。</p></Card><Card title="平台经营信号" sub="聚合证据 → 对应业务页面"><div className="signal"><span>Seller 获客</span><b>{num(K.mql)} → {num(K.deals)}</b><small>观测转化 {pct(K.conversion)}；匹配 {pct(K.match)}</small></div><div className="signal"><span>AI VOC</span><b>{num(K.voc)} 条正文</b><small>主问题 Mixed / Other <strong className="warning">{pct(K.mixed)}</strong></small></div><p className="insight">等待不等于最终未交付。先区分评价时点，再解释履约体验。</p><p className="caption">Exploratory AI · 无人工 Gold Set</p></Card></div></>;
}
function Seller(){
 const [origin,setOrigin]=useState('all');const priority=['paid_search','organic_search','social','email'];const rows=(origin==='all'?[...D.origins]:D.origins.filter(r=>r.origin===origin)).sort((a,b)=>(priority.includes(a.origin)?priority.indexOf(a.origin):99)-(priority.includes(b.origin)?priority.indexOf(b.origin):99));
 return <><Kpis items={[["MQL",num(K.mql),'线索接触期 2017-06 至 2018-05'],['成交 Deals',num(K.deals),'快照中的已观测成交'],['观测转化率',pct(K.conversion),'精确 '+pct(K.conversion,3)+' · 非成熟队列转化'],['匹配 Seller',num(K.matched)+' / '+num(K.deals),pct(K.match)+' 覆盖率']]}/><div className="note-strip"><b>覆盖限制</b>仅 {pct(K.match)} 的成交 Seller 匹配至订单数据。后续表现来自可匹配、窗口成熟子样本。</div>
 <div className="two-col"><Card title="MQL → 成交" sub="保持观测口径；不补造中间阶段"><Chart id="seller-funnel" horizontal labels={['MQL','成交 Deals']} series={[{name:'数量',values:[K.mql,K.deals]}]} max={K.mql} decimals={0} height={222}/><p className="insight">{pct(K.conversion)} 观测转化率，不代表因果效果。</p></Card><Card title="来源转化差异" sub="仅此表筛选；无获客成本，不比较 ROI" actions={<><Select label="Seller Origin" value={origin} onChange={setOrigin} options={[["all","全部来源"],...D.origins.map(r=>[r.origin,r.origin])]}/><button onClick={()=>setOrigin('all')}>重置来源</button></>}><div className="table-scroll"><table id="origin-table"><thead><tr><th>Origin</th><th>MQL</th><th>Deals</th><th>观测转化</th></tr></thead><tbody>{rows.map(r=><tr key={r.origin}><td>{r.origin}</td><td>{num(r.mql)}</td><td>{num(r.deals)}</td><td><b>{pct(r.rate)}</b></td></tr>)}</tbody></table></div><p className="caption">不同来源观测转化不同；没有成本数据，不能判断“最佳渠道”。</p></Card></div>
 <div className="seller-bottom"><Card title="90D 成熟 Seller 的 GMV 分布" sub={'共同成熟样本 n='+num(K.sellerN)+' · BRL'}><Chart id="seller-distribution" horizontal labels={['P25','中位数','P75','均值']} series={[{name:'90D GMV · BRL',values:[K.sellerP25,K.sellerMedian,K.sellerP75,K.sellerMean]}]} decimals={2} height={245}/><p className="caption">均值高于中位数，右偏分布下应同时看两者。</p></Card><Card title="成熟窗口表现" sub="共同成熟 90D · 已验收统计"><div className="stat-pair"><span>中位数 GMV<strong>{num(K.sellerMedian,2)} <small>BRL</small></strong></span><span>平均 GMV<strong>{num(K.sellerMean,2)} <small>BRL</small></strong></span></div><div className="signal"><span>最后 30 天无记录订单</span><b className="warning">{num(K.inactiveN)} / {num(K.sellerN)} · {pct(K.inactive)}</b></div><p className="insight">30D inactivity signal，不称为 churn rate。</p><p className="caption">观测窗口、平台外交易和匹配缺失都限制解释；不把未记录订单视为确定流失。</p></Card></div></>;
}
function Customer(){return <><Kpis items={[["观测复购率",pct(K.repeat),num(K.repeatCount)+' / '+num(K.customers)],['共同成熟 90D',pct(K.rep90),'共同成熟用户 n='+num(K.repDen)],['90D · ≥24h敏感性',pct(K.rep24),'购买时间间隔 ≥24h；不是复购真值'],['仅一单用户',pct(K.oneTime),'核心窗口内观测订单数']]}/><div className="two-col"><Card title="共同成熟窗口的累计复购" sub={'同一批 '+num(K.repDen)+' 位用户，30D ≤ 60D ≤ 90D'}><Chart id="repurchase-horizons" kind="line" percent max={3} decimals={2} height={250} labels={D.repurchase.map(r=>r.days+'D')} series={[{name:'累计复购',values:D.repurchase.map(r=>r.rate*100)}]}/><p className="caption">窗口增大时累计比例不下降；不是三个不同成熟队列拼接。</p></Card><Card title="90D 定义敏感性" sub="同一成熟样本，不将 24h 阈值当作真值"><Chart id="repurchase-sensitivity" horizontal percent max={3} decimals={2} height={235} labels={['严格较晚订单','购买时间间隔 ≥24h']} series={[{name:'90D 复购',color:blue,values:[K.rep90*100,K.rep24*100]}]}/><p className="caption">沿用已验收层 购买时间间隔 ≥24h 规则；24h threshold is sensitivity analysis, not ground truth.</p></Card></div><div className="two-col"><Card title="客户结构：订单频次 × 支出" sub={'样本内支出 P75 = '+num(K.p75)+' BRL，不是通用业务阈值'}><Chart id="customer-structure" horizontal percent max={80} decimals={2} height={255} labels={D.customerSegments.map(r=>({'High-value One-time':'≥P75 · 仅一单','High-value Repeat':'≥P75 · 复购','One-time':'低于P75 · 仅一单','Repeat':'低于P75 · 复购'}[r.segment]||r.segment))} series={[{name:'客户占比',values:D.customerSegments.map(r=>r.share*100)}]}/><p className="caption">互斥客户组，分母 {num(K.customers)}；高支出组沿用原分析分段。</p></Card><Card title="RFM 的适用边界" sub="保留方法限制，避免强行分组"><div className="big-stat">{pct(K.oneTime,0)}<span>用户在窗口内只有一单</span></div><p className="insight">不强行构造 Frequency 五分位。</p><p>观测频次集中在 1，机械切分容易制造没有经营区分度的层级。本项目保留订单频次与样本支出阈值的透明分组。</p><p className="caption">低复购是观测现象。平台外购买、品类购买周期及观察截尾，不能由当前数据单独识别为原因。</p></Card></div></>;}
function Fulfillment(){
 const [timing,setTiming]=useState('all'),[category,setCategory]=useState('all'),[minN,setMinN]=useState('100');const score=timing==='all'?D.scoreTiming:D.scoreTiming.slice(1);const categories=D.categories.filter(r=>(category==='all'||r.category===category)&&r.reviewN>=Number(minN));
 return <><Kpis items={[["迟到率",pct(K.late),num(K.lateN)+' / '+num(K.lateDen)+' 有效日期订单'],['未迟到均分',num(K.ontimeScore,3),'全部代表评价 n='+num(D.scoreTiming[0].ontimeN)],['迟到均分',num(K.lateScore,3),'全部代表评价 n='+num(D.scoreTiming[0].lateN)],['签收后调整 OR',num(K.or,2),'95% CI '+num(K.orLow,2)+'–'+num(K.orHigh,2)]]}/><div className="two-col"><Card title="月度迟到率" sub="购买月 · 有效日期已签收订单"><Chart id="monthly-late" kind="line" percent max={20} decimals={2} height={235} labels={D.lateMonthly.map(r=>r.month)} series={[{name:'迟到率',values:D.lateMonthly.map(r=>r.rate*100)}]}/><p className="caption">2018-03 值得回查；当前数据不自动解释异常原因。</p></Card><Card title="评价时点与评分差异" sub="签收后按 review_answer_timestamp 判断，沿用原规则" actions={<Select label="评价时点" value={timing} onChange={setTiming} options={[["all","两种口径对照"],["after","只看签收后"]]}/> }><Chart id="score-timing" labels={score.map(r=>r.scope)} series={[{name:'迟到',values:score.map(r=>r.late),color:amber},{name:'未迟到',values:score.map(r=>r.ontime),color:teal}]} legend max={5} decimals={3} height={215}/><p className="caption">{score.map(r=>r.scope+'：迟到 n='+num(r.lateN)+' / 未迟到 n='+num(r.ontimeN)).join('；')}</p></Card></div><div className="two-col"><Card title="品类 CX 诊断" sub="仅此表筛选；订单/品类口径不可跨类加总" actions={<><Select label="品类" value={category} onChange={setCategory} options={[["all","全部品类"],...D.categories.map(r=>[r.category,r.category])]}/><label className="filter">最小评价数<input aria-label="最小评价数" type="number" min="0" value={minN} onChange={e=>setMinN(e.target.value)}/></label><button onClick={()=>{setCategory('all');setMinN('100');}}>重置品类</button></>}><div className="table-scroll">{categories.length?<table id="category-table"><thead><tr><th>品类</th><th>评价 N</th><th>均分</th><th>迟到率</th></tr></thead><tbody>{categories.map(r=><tr key={r.category}><td>{r.category}</td><td>{num(r.reviewN)}</td><td>{num(r.score,3)}</td><td title={num(r.lateN)+' / '+num(r.lateDen)}>{pct(r.late)}</td></tr>)}</tbody></table>:<div className="no-data" role="status">No data for selected filters<br/>当前筛选无数据，请重置。</div>}</div></Card><Card title="签收后关联与品类信号" sub="Association only · Not causal effect"><div className="or-row"><b>OR {num(K.or,2)}</b><span>95% CI {num(K.orLow,2)}–{num(K.orHigh,2)}<br/>不是概率倍数；保留协变量控制口径。</span></div><Office/></Card></div></>;
}
function AI(){
 const [role,setRole]=useState('primary'),[issue,setIssue]=useState('all');const rows=D.issues.filter(r=>r.role===role&&(issue==='all'||r.issue===issue)).sort((a,b)=>b.n-a.n);
 return <><Kpis items={[["Canonical 正文",num(K.voc),'语料：全部日期的 canonical 正文'],['主问题 · 评分≤3',num(K.primary),'Semantic issue discovery'],['正向 · 评分≥4',num(K.positive),'补充正向体验'],['主问题 Mixed / Other',pct(K.mixed),'保守包含宽商品混合簇']]}/><div className="pipeline">{[num(K.voc)+' 条正文','Multilingual Embedding','语义聚类','AI 辅助主题命名','结构化验证'].map((x,i)=><React.Fragment key={x}><b>{x}</b>{i<4&&<span>→</span>}</React.Fragment>)}</div><div className="ai-grid"><Card title="评价时点实质改变解释" sub="等待／尚未收到主题 · 核心正文迟到率"><Hero/></Card><Card title="语义主题分布" sub="主题为簇级近似；N来自当前语料组" actions={<><Select label="语料组" value={role} onChange={v=>{setRole(v);setIssue('all');}} options={[["primary","主问题语料"],["positive","正向语料"]]}/><Select label="Issue Category" value={issue} onChange={setIssue} options={[["all","全部主题"],...D.issues.filter(r=>r.role===role).map(r=>[r.issue,issueNames[r.issue]])]}/></>}><Chart id="issue-distribution" horizontal labels={rows.map(r=>issueNames[r.issue])} series={[{name:'评论 N',values:rows.map(r=>r.n),pointColors:rows.map(r=>r.role==='primary'&&!['Delivery waiting / non-receipt','Incomplete order / missing units'].includes(r.issue)?gray:teal)}]} decimals={0} height={254}/><p className="caption">当前显示 {num(rows.reduce((n,r)=>n+r.n,0))} 条；迟到验证与正文数量采用不同范围，见下方数据。</p><details className="data-table"><summary>查看主题的结构化验证</summary><table><thead><tr><th>主题</th><th>核心迟到 N / 分母</th><th>迟到率</th></tr></thead><tbody>{rows.map(r=><tr key={r.issue}><td>{issueNames[r.issue]}</td><td>{num(r.lateN)} / {num(r.lateDen)}</td><td>{pct(r.late)}</td></tr>)}</tbody></table></details><button className="text-button" onClick={()=>{setRole('primary');setIssue('all');}}>重置主题</button></Card><Card title="Office Furniture · 诊断信号" sub="仅比较主问题正文内部结构"><Office/></Card><Card title="如何阅读 AI 证据" sub={'Multilingual MiniLM · '+K.embeddingDim+' dimensions'}><p className="insight">{pct(K.waitAll)} 是主题内迟到率，不是最终交付失败率。</p><p>评论中的“等待／未收到”概括了评价时点的表达，不能直接推断最终交付状态。</p><div className="method"><b>Exploratory AI</b><ul><li>No Human Gold Set；未经独立人工标注验证。</li><li>葡萄牙语评论；语义聚类与簇级映射有误差。</li><li>Review Self-selection；有正文用户不代表全体。</li><li>Mixed / Other {pct(K.mixed)}，不隐藏混合类别。</li><li>Correlation ≠ Causation；保留评价时点限制。</li></ul></div></Card></div></>;
}
function App(){const getPage=()=>Math.max(0,routes.indexOf(location.hash.slice(2)));const [page,setPage]=useState(getPage);useEffect(()=>{const h=()=>{setPage(getPage());window.scrollTo(0,0);};window.addEventListener('hashchange',h);return()=>window.removeEventListener('hashchange',h);},[]);const pages=[Overview,Seller,Customer,Fulfillment,AI];const Component=pages[page];return <><a className="skip" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById("main-content").focus();}}>跳到内容</a><aside><div className="brand">MARKET / LAB<small>OLIST · BUSINESS ANALYTICS</small></div><nav aria-label="主导航">{titles.map((t,i)=><a key={t} href={'#/'+routes[i]} aria-current={page===i?'page':undefined}><span>{String(i+1).padStart(2,'0')}</span>{t}</a>)}</nav><div className="sidebar-foot">ANALYSIS WINDOW<br/><b>Jan 2017 — Jul 2018</b><br/><br/>PORTFOLIO / ANALYTICS</div></aside><main id="main-content" tabIndex="-1"><header><div><div className="eyebrow">MARKETPLACE INTELLIGENCE / {String(page+1).padStart(2,'0')}</div><h1>{titles[page]}</h1><p>{subtitles[page]}</p></div><div className="scope"><b>{page===4?'语料：全部日期 / 验证：核心窗口':page===1?'线索接触期：2017-06 至 2018-05':'核心窗口：2017-01 至 2018-07'}</b><small>{page===4?'核心验证：2017-01 至 2018-07 · 已签收':'全期 KPI 固定；模块内筛选仅影响对应图表'}</small></div></header><Component key={page}/><footer>OLIST / 已验收聚合指标 · 各模块保留分母与方法限制 <span>本地静态 Dashboard · 无追踪</span></footer></main></>;}
createRoot(document.getElementById('root')).render(<App/>);
