const {chromium}=require('playwright');
const fs=require('fs');const path=require('path');const root=path.resolve(__dirname,'../..');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1080}});let errors=[],requests=[],qa=[],layout=[];
page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('request',r=>requests.push(r.url()));
const check=(name,ok,detail='')=>{qa.push({check:name,status:ok?'PASS':'FAIL',detail});if(!ok)console.log('FAIL',name,detail)};
await page.goto('http://127.0.0.1:4173/#/overview');await page.locator('#monthly-trend svg').waitFor();
const nav=['overview','seller','customer','fulfillment','ai-voc'];
for(let i=0;i<nav.length;i++){
 await page.locator('nav a').nth(i).click();await page.waitForTimeout(350);check('navigation '+nav[i],page.url().endsWith('#/'+nav[i]));
 let m=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth,sidebar:document.querySelector('aside').getBoundingClientRect().width,header:document.querySelector('header').getBoundingClientRect().height,cards:[...document.querySelectorAll('.card')].map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})),overflow:[...document.querySelectorAll('.kpi strong,h1,h2')].filter(e=>e.scrollWidth>e.clientWidth+2).map(e=>e.textContent)}));layout.push({page:nav[i],width:1440,...m});check('1440 overflow '+nav[i],m.scroll<=m.width&&m.overflow.length===0,JSON.stringify(m.overflow));check('OptionB sidebar '+nav[i],m.sidebar===208);check('charts rendered '+nav[i],await page.locator('.chart svg').count()>0);
 await page.screenshot({path:`${root}/assets/session5/screenshots/0${i+1}_${i===4?'ai_voc':nav[i]}_1440.png`,fullPage:true});
 await page.setViewportSize({width:1280,height:1000});await page.waitForTimeout(200);let n=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth,overflow:[...document.querySelectorAll('.kpi strong,h1,h2')].filter(e=>e.scrollWidth>e.clientWidth+2).map(e=>e.textContent)}));check('1280 overflow '+nav[i],n.scroll<=n.width&&n.overflow.length===0,JSON.stringify(n));await page.screenshot({path:`${root}/assets/session5/screenshots/0${i+1}_${i===4?'ai_voc':nav[i]}_1280.png`,fullPage:true});await page.setViewportSize({width:1440,height:1080});
}
await page.locator('nav a').nth(0).click();await page.waitForTimeout(180);const before=await page.locator('#monthly-trend').getAttribute('data-series');await page.getByLabel('趋势指标').selectOption('orders');await page.waitForTimeout(180);check('trend selector changes series',before!==await page.locator('#monthly-trend').getAttribute('data-series'));const labels=(await page.locator('#monthly-trend').getAttribute('data-labels')).split('|');check('browser month ticks distinct',labels.length===19&&new Set(labels).size===19&&labels[0]==='2017-01'&&labels.at(-1)==='2018-07');const ticks=(await page.locator('#monthly-trend svg text').allTextContents()).filter(t=>/^20\d{2}-\d{2}$/.test(t));check('actual SVG date labels',new Set(ticks).size>1&&ticks.includes('2017-01')&&ticks.includes('2018-07')&&new Set(ticks).size===ticks.length,JSON.stringify(ticks));
const box=await page.locator('#monthly-trend').boundingBox();await page.mouse.move(box.x+box.width*.57,box.y+box.height*.5);await page.waitForTimeout(180);const tips=await page.locator('#monthly-trend div').evaluateAll(ds=>ds.filter(d=>d.style.position==='absolute'&&getComputedStyle(d).visibility!=='hidden'&&getComputedStyle(d).display!=='none'&&d.innerText.includes(':')).map(d=>d.innerText));check('tooltip and hover',tips.length>0&&tips.some(t=>t.includes('订单:')),JSON.stringify(tips));
await page.locator('nav a').nth(1).click();await page.getByLabel('Seller Origin').selectOption('paid_search');check('origin filter',await page.locator('#origin-table tbody tr').count()===1&&(await page.locator('#origin-table').innerText()).includes('paid_search'));await page.getByRole('button',{name:'重置来源'}).click();check('origin reset',await page.locator('#origin-table tbody tr').count()>4);await page.getByLabel('Seller Origin').focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');check('keyboard filter',await page.locator('#origin-table tbody tr').count()===1);await page.getByRole('button',{name:'重置来源'}).click();
await page.locator('nav a').nth(3).click();await page.getByLabel('评价时点',{exact:true}).selectOption('after');check('timing filter',await page.locator('#score-timing').getAttribute('data-labels')==='签收后作答评价');
await page.getByLabel('品类',{exact:true}).selectOption('office_furniture');check('category filter',await page.locator('#category-table tbody tr').count()===1);await page.getByLabel('最小评价数').fill('999999');check('no-data state',await page.getByRole('status').isVisible());await page.getByRole('button',{name:'重置品类'}).click();check('category reset',await page.locator('#category-table tbody tr').count()>1);
await page.getByLabel('评价时点',{exact:true}).selectOption('all');await page.waitForTimeout(200);const legend=page.locator('#score-timing svg text').filter({hasText:/^迟到$/}).first();const shapes=await page.locator('#score-timing svg path').count();await legend.click();await page.waitForTimeout(180);check('legend toggles series',await page.locator('#score-timing svg path').count()!==shapes,'SVG path count before '+shapes+' after '+await page.locator('#score-timing svg path').count());
await page.locator('nav a').nth(4).click();await page.getByLabel('语料组',{exact:true}).selectOption('positive');check('positive theme filter',(await page.locator('#issue-distribution').getAttribute('data-labels')).split('|').length===3);await page.getByLabel('Issue Category').selectOption('Positive generic mentions');check('issue filter',(await page.locator('#issue-distribution').getAttribute('data-labels'))==='泛化好评');await page.getByRole('button',{name:'重置主题'}).click();check('issue reset',(await page.locator('#issue-distribution').getAttribute('data-labels')).split('|').length===6);
await page.locator('nav a').nth(2).focus();await page.keyboard.press('Enter');check('keyboard navigation',page.url().endsWith('#/customer'));await page.locator('summary').first().focus();await page.keyboard.press('Enter');check('keyboard chart data',await page.locator('details').first().getAttribute('open')!==null);
await page.reload();await page.waitForTimeout(220);check('hash refresh',await page.locator('h1').innerText()==='客户价值');await page.locator('.skip').focus();await page.keyboard.press('Enter');check('skip link preserves route and focuses main',page.url().endsWith('#/customer')&&await page.locator('main').evaluate(e=>e===document.activeElement));check('console errors',errors.length===0,JSON.stringify(errors));check('no external requests',requests.every(u=>u.startsWith('http://127.0.0.1:4173/')),JSON.stringify([...new Set(requests)]));
fs.writeFileSync(`${root}/outputs/session5_browser_results.json`,JSON.stringify({qa,layout,errors,requests:[...new Set(requests)]},null,2));console.log(qa.map(r=>r.status).reduce((a,v)=>(a[v]=(a[v]||0)+1,a),{}));await browser.close();})();